version:  '2'

services:
    php:
        image: lephare/php:7.0
        volumes:
            - .:/var/www/symfony

    web:
        image: lephare/apache:2.4
        ports:
            - 8000:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/apache:/var/log/apache2
        environment:
            DOCUMENT_ROOT: /var/www/symfony
